/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v10.0
processor: MIMXRT1052xxxxB
package_id: MIMXRT1052CVL5B
mcu_data: ksdk2_0
processor_version: 10.0.0
pin_labels:
- {pin_num: J2, pin_signal: GPIO_SD_B0_05, label: EPD_DC, identifier: EPD_DC}
- {pin_num: M4, pin_signal: GPIO_SD_B1_03, label: EPD_RES, identifier: EPD_RES}
- {pin_num: K1, pin_signal: GPIO_SD_B0_03, label: EPD_RES, identifier: EPD_RES}
- {pin_num: H2, pin_signal: GPIO_SD_B0_04, label: EPD_BUSY, identifier: EPD_BUSY}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: J3, peripheral: LPSPI1, signal: PCS0, pin_signal: GPIO_SD_B0_01}
  - {pin_num: J4, peripheral: LPSPI1, signal: SCK, pin_signal: GPIO_SD_B0_00}
  - {pin_num: J1, peripheral: LPSPI1, signal: SDO, pin_signal: GPIO_SD_B0_02}
  - {pin_num: J2, peripheral: GPIO3, signal: 'gpio_io, 17', pin_signal: GPIO_SD_B0_05, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: K1, peripheral: GPIO3, signal: 'gpio_io, 15', pin_signal: GPIO_SD_B0_03, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: H2, peripheral: GPIO3, signal: 'gpio_io, 16', pin_signal: GPIO_SD_B0_04, direction: INPUT, gpio_interrupt: kGPIO_IntRisingEdge, pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Pull, open_drain: Enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  /* GPIO configuration of EPD_RES on GPIO_SD_B0_03 (pin K1) */
  gpio_pin_config_t EPD_RES_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 1U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_SD_B0_03 (pin K1) */
  GPIO_PinInit(GPIO3, 15U, &EPD_RES_config);

  /* GPIO configuration of EPD_BUSY on GPIO_SD_B0_04 (pin H2) */
  gpio_pin_config_t EPD_BUSY_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntRisingEdge
  };
  /* Initialize GPIO functionality on GPIO_SD_B0_04 (pin H2) */
  GPIO_PinInit(GPIO3, 16U, &EPD_BUSY_config);
  /* Enable GPIO pin interrupt on GPIO_SD_B0_04 (pin H2) */
  GPIO_PortEnableInterrupts(GPIO3, 1U << 16U);

  /* GPIO configuration of EPD_DC on GPIO_SD_B0_05 (pin J2) */
  gpio_pin_config_t EPD_DC_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 1U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_SD_B0_05 (pin J2) */
  GPIO_PinInit(GPIO3, 17U, &EPD_DC_config);

  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_00_LPSPI1_SCK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_01_LPSPI1_PCS0, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_02_LPSPI1_SDO, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_03_GPIO3_IO15, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_04_GPIO3_IO16, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_05_GPIO3_IO17, 0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_04_GPIO3_IO16, 0xB8B0U); 
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
