/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_SD_B0_05 (coord J2), EPD_DC */
/* Routed pin properties */
#define BOARD_INITPINS_EPD_DC_PERIPHERAL                                   GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_EPD_DC_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_EPD_DC_CHANNEL                                        17U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_EPD_DC_GPIO                                         GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_EPD_DC_GPIO_PIN                                       17U   /*!< GPIO pin number */
#define BOARD_INITPINS_EPD_DC_GPIO_PIN_MASK                          (1U << 17U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_EPD_DC_PORT                                         GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_EPD_DC_PIN                                            17U   /*!< PORT pin number */
#define BOARD_INITPINS_EPD_DC_PIN_MASK                               (1U << 17U)   /*!< PORT pin mask */

/* GPIO_SD_B0_03 (coord K1), EPD_RES */
/* Routed pin properties */
#define BOARD_INITPINS_EPD_RES_PERIPHERAL                                  GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_EPD_RES_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_EPD_RES_CHANNEL                                       15U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_EPD_RES_GPIO                                        GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_EPD_RES_GPIO_PIN                                      15U   /*!< GPIO pin number */
#define BOARD_INITPINS_EPD_RES_GPIO_PIN_MASK                         (1U << 15U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_EPD_RES_PORT                                        GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_EPD_RES_PIN                                           15U   /*!< PORT pin number */
#define BOARD_INITPINS_EPD_RES_PIN_MASK                              (1U << 15U)   /*!< PORT pin mask */

/* GPIO_SD_B0_04 (coord H2), EPD_BUSY */
/* Routed pin properties */
#define BOARD_INITPINS_EPD_BUSY_PERIPHERAL                                 GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_EPD_BUSY_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_EPD_BUSY_CHANNEL                                      16U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_EPD_BUSY_GPIO                                       GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_EPD_BUSY_GPIO_PIN                                     16U   /*!< GPIO pin number */
#define BOARD_INITPINS_EPD_BUSY_GPIO_PIN_MASK                        (1U << 16U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_EPD_BUSY_PORT                                       GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_EPD_BUSY_PIN                                          16U   /*!< PORT pin number */
#define BOARD_INITPINS_EPD_BUSY_PIN_MASK                             (1U << 16U)   /*!< PORT pin mask */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
